name: monome
description: Basic monome abstractions for Dart.
version: 0.0.1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  osc:
    git: git://github.com/pq/osc.git

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
